<?php

namespace App\Services;

use App\Models\Router;
use App\Models\Voucher;
use App\Models\VoucherProfile;
use Exception;
use Illuminate\Support\Facades\Log;

class VoucherService
{
    /**
     * Sync Voucher Profile to Mikrotik Hotspot User Profile.
     */
    public function syncProfile(Router $router, VoucherProfile $profile): bool
    {
        Log::info("Mikrotik Hotspot: Syncing profile {$profile->name} to router {$router->name} ({$router->ip_address})");
        
        // Clean rate-limit
        $cleanedLimit = str_replace(' ', '', $profile->bandwidth_limit);

        try {
            $client = $this->getClient($router);

            // Check if profile exists
            $query = (new \RouterOS\Query('/ip/hotspot/user/profile/print'))
                ->where('name', $profile->name);
            $responses = $client->query($query)->read();

            $params = [
                'name' => $profile->name,
                'rate-limit' => $cleanedLimit,
                'shared-users' => (string) $profile->shared_users,
                'status-autorefresh' => '1m',
            ];

            if (empty($responses)) {
                Log::info("Mikrotik Hotspot: Creating new profile {$profile->name}");
                // Create
                $addQuery = new \RouterOS\Query('/ip/hotspot/user/profile/add');
                foreach ($params as $key => $value) {
                    $addQuery->equal($key, $value);
                }
                $response = $client->query($addQuery)->read();
                if (isset($response['!trap'])) {
                    Log::error("Mikrotik Hotspot API Error (Add Profile): " . json_encode($response));
                    return false;
                }
            } else {
                Log::info("Mikrotik Hotspot: Updating existing profile {$profile->name}");
                // Update
                $id = $responses[0]['.id'];
                $setQuery = new \RouterOS\Query('/ip/hotspot/user/profile/set');
                $setQuery->equal('.id', $id);
                foreach ($params as $key => $value) {
                    $setQuery->equal($key, $value);
                }
                $response = $client->query($setQuery)->read();
                if (isset($response['!trap'])) {
                    Log::error("Mikrotik Hotspot API Error (Set Profile): " . json_encode($response));
                    return false;
                }
            }

            return true;
        } catch (Exception $e) {
            Log::error("Voucher Profile Sync Exception: " . $e->getMessage());
            return false;
        }
    }

    /**
     * Delete Voucher Profile from Mikrotik.
     */
    public function deleteProfile(Router $router, string $profileName): bool
    {
        try {
            $client = $this->getClient($router);
            $query = (new \RouterOS\Query('/ip/hotspot/user/profile/print'))
                ->where('name', $profileName);
            $responses = $client->query($query)->read();

            if (!empty($responses)) {
                $id = $responses[0]['.id'];
                $removeQuery = (new \RouterOS\Query('/ip/hotspot/user/profile/remove'))
                    ->equal('.id', $id);
                $client->query($removeQuery)->read();
            }
            return true;
        } catch (Exception $e) {
            Log::error("Voucher Profile Delete Failed: " . $e->getMessage());
            return false;
        }
    }

    /**
     * Sync Voucher (User) to Mikrotik Hotspot User.
     */
    public function syncVoucher(Voucher $voucher): bool
    {
        $router = $voucher->router;
        if (!$router) return false;

        Log::info("Mikrotik Hotspot: Syncing voucher {$voucher->code} to router {$router->name}");

        try {
            $client = $this->getClient($router);

            // Check if user exists
            $query = (new \RouterOS\Query('/ip/hotspot/user/print'))
                ->where('name', $voucher->code);
            $responses = $client->query($query)->read();

            $params = [
                'name' => $voucher->code,
                'password' => $voucher->code, // Simple: code is both user and pass
                'profile' => $voucher->profile->name,
                'limit-uptime' => $voucher->profile->validity,
                'comment' => $voucher->comment ?? 'Generated by App',
            ];

            if (empty($responses)) {
                Log::info("Mikrotik Hotspot: Creating new user {$voucher->code}");
                // Create
                $addQuery = new \RouterOS\Query('/ip/hotspot/user/add');
                foreach ($params as $key => $value) {
                    $addQuery->equal($key, $value);
                }
                $response = $client->query($addQuery)->read();
                if (isset($response['!trap'])) {
                    Log::error("Mikrotik Hotspot API Error (Add User): " . json_encode($response));
                    return false;
                }
            } else {
                Log::info("Mikrotik Hotspot: Updating existing user {$voucher->code}");
                // Update
                $id = $responses[0]['.id'];
                $setQuery = new \RouterOS\Query('/ip/hotspot/user/set');
                $setQuery->equal('.id', $id);
                foreach ($params as $key => $value) {
                    $setQuery->equal($key, $value);
                }
                $response = $client->query($setQuery)->read();
                if (isset($response['!trap'])) {
                    Log::error("Mikrotik Hotspot API Error (Set User): " . json_encode($response));
                    return false;
                }
            }

            return true;
        } catch (Exception $e) {
            Log::error("Voucher Sync Exception: " . $e->getMessage());
            return false;
        }
    }

    /**
     * Delete Voucher (User) from Mikrotik.
     */
    public function deleteVoucher(Voucher $voucher): bool
    {
        $router = $voucher->router;
        if (!$router) return false;

        try {
            $client = $this->getClient($router);
            $query = (new \RouterOS\Query('/ip/hotspot/user/print'))
                ->where('name', $voucher->code);
            $responses = $client->query($query)->read();

            if (!empty($responses)) {
                $id = $responses[0]['.id'];
                $removeQuery = (new \RouterOS\Query('/ip/hotspot/user/remove'))
                    ->equal('.id', $id);
                $client->query($removeQuery)->read();
            }
            return true;
        } catch (Exception $e) {
            Log::error("Voucher Delete Failed: " . $e->getMessage());
            return false;
        }
    }

    /**
     * Helper to get Mikrotik Client.
     */
    protected function getClient(Router $router): \RouterOS\Client
    {
        $config = new \RouterOS\Config([
            'host' => $router->ip_address,
            'user' => $router->username,
            'pass' => $router->password,
            'port' => $router->port ?? 8728,
        ]);
        return new \RouterOS\Client($config);
    }
}
