<?php

namespace App\Services;

use App\Models\Router;
use App\Models\Voucher;
use App\Models\VoucherProfile;
use Exception;
use Illuminate\Support\Facades\Log;

class VoucherService
{
    /**
     * Sync Voucher Profile to Mikrotik Hotspot User Profile.
     */
    public function syncProfile(Router $router, VoucherProfile $profile): bool
    {
        try {
            $client = $this->getClient($router);

            // Check if profile exists
            $query = (new \RouterOS\Query('/ip/hotspot/user/profile/print'))
                ->where('name', $profile->name);
            $responses = $client->query($query)->read();

            $params = [
                'name' => $profile->name,
                'rate-limit' => $profile->bandwidth_limit,
                'shared-users' => (string) $profile->shared_users,
                'status-autorefresh' => '1m',
            ];

            if (empty($responses)) {
                // Create
                $addQuery = new \RouterOS\Query('/ip/hotspot/user/profile/add');
                foreach ($params as $key => $value) {
                    $addQuery->equal($key, $value);
                }
                $client->query($addQuery)->read();
            } else {
                // Update
                $id = $responses[0]['.id'];
                $setQuery = new \RouterOS\Query('/ip/hotspot/user/profile/set');
                $setQuery->equal('.id', $id);
                foreach ($params as $key => $value) {
                    $setQuery->equal($key, $value);
                }
                $client->query($setQuery)->read();
            }

            return true;
        } catch (Exception $e) {
            Log::error("Voucher Profile Sync Failed: " . $e->getMessage());
            return false;
        }
    }

    /**
     * Delete Voucher Profile from Mikrotik.
     */
    public function deleteProfile(Router $router, string $profileName): bool
    {
        try {
            $client = $this->getClient($router);
            $query = (new \RouterOS\Query('/ip/hotspot/user/profile/print'))
                ->where('name', $profileName);
            $responses = $client->query($query)->read();

            if (!empty($responses)) {
                $id = $responses[0]['.id'];
                $removeQuery = (new \RouterOS\Query('/ip/hotspot/user/profile/remove'))
                    ->equal('.id', $id);
                $client->query($removeQuery)->read();
            }
            return true;
        } catch (Exception $e) {
            Log::error("Voucher Profile Delete Failed: " . $e->getMessage());
            return false;
        }
    }

    /**
     * Sync Voucher (User) to Mikrotik Hotspot User.
     */
    public function syncVoucher(Voucher $voucher): bool
    {
        $router = $voucher->router;
        if (!$router) return false;

        try {
            $client = $this->getClient($router);

            // Check if user exists
            $query = (new \RouterOS\Query('/ip/hotspot/user/print'))
                ->where('name', $voucher->code);
            $responses = $client->query($query)->read();

            $params = [
                'name' => $voucher->code,
                'password' => $voucher->code, // Simple: code is both user and pass
                'profile' => $voucher->profile->name,
                'limit-uptime' => $voucher->profile->validity,
                'comment' => $voucher->comment ?? 'Generated by App',
            ];

            if (empty($responses)) {
                // Create
                $addQuery = new \RouterOS\Query('/ip/hotspot/user/add');
                foreach ($params as $key => $value) {
                    $addQuery->equal($key, $value);
                }
                $client->query($addQuery)->read();
            } else {
                // Update
                $id = $responses[0]['.id'];
                $setQuery = new \RouterOS\Query('/ip/hotspot/user/set');
                $setQuery->equal('.id', $id);
                foreach ($params as $key => $value) {
                    $setQuery->equal($key, $value);
                }
                $client->query($setQuery)->read();
            }

            return true;
        } catch (Exception $e) {
            Log::error("Voucher Sync Failed: " . $e->getMessage());
            return false;
        }
    }

    /**
     * Delete Voucher (User) from Mikrotik.
     */
    public function deleteVoucher(Voucher $voucher): bool
    {
        $router = $voucher->router;
        if (!$router) return false;

        try {
            $client = $this->getClient($router);
            $query = (new \RouterOS\Query('/ip/hotspot/user/print'))
                ->where('name', $voucher->code);
            $responses = $client->query($query)->read();

            if (!empty($responses)) {
                $id = $responses[0]['.id'];
                $removeQuery = (new \RouterOS\Query('/ip/hotspot/user/remove'))
                    ->equal('.id', $id);
                $client->query($removeQuery)->read();
            }
            return true;
        } catch (Exception $e) {
            Log::error("Voucher Delete Failed: " . $e->getMessage());
            return false;
        }
    }

    /**
     * Helper to get Mikrotik Client.
     */
    protected function getClient(Router $router): \RouterOS\Client
    {
        $config = new \RouterOS\Config([
            'host' => $router->ip_address,
            'user' => $router->username,
            'pass' => $router->password,
            'port' => $router->port ?? 8728,
        ]);
        return new \RouterOS\Client($config);
    }
}
